name: template_mobile
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  aad_oauth: ^0.3.0
  animated_splash_screen: ^1.1.0
  auto_size_text: ^3.0.0-nullsafety.0
  badges: ^2.0.2
  build_runner: ^2.1.1
  cupertino_icons: ^1.0.2
  custom_searchable_dropdown: ^2.1.0
  date_time_picker: ^2.1.0
  dio: ^4.0.0
  easy_localization: ^3.0.0
  equatable: ^2.0.3
  fast_immutable_collections: ^7.0.3
  file_picker: ^4.1.1
  flutter:
    sdk: flutter
  flutter_form_builder: ^6.1.0+1
  flutter_mobx: ^2.0.2
  flutter_multi_formatter: ^2.4.4
  flutter_multiselect: ^1.0.0
  flutter_screenutil: ^5.0.1
  flutter_slidable: ^0.6.0
  flutter_svg: ^0.22.0
  footer: ^0.0.4
  get: ^4.3.8
  http: ^0.13.3
  image_picker: any
  json_annotation: ^4.1.0
  json_serializable: ^5.0.0
  mime: ^1.0.1
  mime_type: ^1.0.0
  mobx: ^2.0.4
  mobx_codegen: ^2.0.3
  multi_select_flutter: ^4.0.0
  numberpicker: ^2.1.1
  path: ^1.8.0
  path_provider: any
  popover: ^0.2.6+3
  provider: ^6.0.0
  shared_preferences: ^2.0.7
  webview_flutter: ^2.0.4
  flutter_launcher_icons: ^0.9.3
  
dependency_overrides:
  analyzer: ^3.1.0
  meta: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter 
flutter_icons:
    android: true
    ios: true
    image_path: "assets/image/logo.png"
    adaptive_icon_foreground: "assets/image/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
    - assets/svg/
    - assets/image/
    - assets/lottie/
    - assets/pics/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf