enum PreferencesKeys {
  TOKEN,
  IS_FIRST_APP,
  PASSWORD,
  ACCESSTOKEN_SAFETYTOUR,
  ACCESSTOKEN_ESD,
  ACCESSTOKEN_MOC,
  USER_MAIL,
  USER_NAME,
  REMEMBER_CLIENT,
  ACCESSTOKEN_AZUREAD,
  ESD_TOKEN_EXPIRE_TIME,
  MOC_TOKEN_EXPIRE_TIME,
  SAFETY_TOUR_TOKEN_EXPIRE_TIME
}
